[package]
name = "scan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = { version = "2", default-features = false }

[target.'cfg(unix)'.dependencies.goblin]
version = "0.5.1"
default-features = false
features = ["elf64", "elf32", "endian_fd"]

[target.'cfg(windows)'.dependencies.goblin]
version = "0.5.1"
default-features = false
features = ["pe64", "pe32", "endian_fd"]

# [dependencies.windows-sys]
# version = "0.36.1"
# features = [
#     "Win32_Foundation",
#     "Win32_System_Diagnostics_Debug"
# ]

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.36.1"
features = ["Win32_Foundation", "Win32_System_Diagnostics_Debug"]

[profile.dev]
# strip = true

[profile.release]
# debug = true
lto = true
codegen-units = 1
panic = "abort"
strip = true
