[package]
name = "lince"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# name = "lince"
# crate-type = ["cdylib"]

[[bin]]
bench = false
path = "src/main.rs"
name = "lince"

[[bench]]
name = "integration_bench"
path = "bench/benchs.rs"

[[test]]
name = "integration_test"
path = "tests/tests.rs"

[dependencies]
memchr = { version = "2" }
dashmap = "5.1.0"
# walkdir = "2"
# rustyline = "9.1.0"
# colored = "2"

# [profile.release]
# lto = true
# codegen-units = 1
# panic = "abort"
# strip = true

[profile.dev]