[package]
name = "lince"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# name = "lince"
# crate-type = ["cdylib"]

[[bin]]
bench = false
path = "src/main.rs"
name = "lince"

[[bench]]
name = "integration_bench"
path = "bench/benchs.rs"

[[test]]
name = "integration_test"
path = "tests/tests.rs"

[dependencies]
memchr = { version = "2", default-features = false }
# fltk = "^1.3"
# sysinfo = "0.23.5"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
