[package]
name = "meow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.serde]
version = "1.0.137"
default-features = false
features = ["derive"]

[dependencies.bincode]
version = "1.3.3"
default-features = false

[dependencies.utils]
version = "*"
path = "utils"
features = ["log", "dev"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
